on:
  push:

env:
  AAAA: sinofseven

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo sinofseven
      - run: |
          echo "::add-mask::sinofseven"
          echo sinofseven
      - run: echo sinofseven
